# Generated by Django 4.0.5 on 2022-07-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('nomav', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('modelav', models.CharField(max_length=30)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('myphone', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('voyid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('depart', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('datedep', models.DateTimeField()),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.avion')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('num', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('msg', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.utilisateur')),
            ],
        ),
    ]
