# Generated by Django 4.0.5 on 2022-07-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Dashboard.utilisateur')),
                ('num', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('carddate', models.DateField()),
            ],
        ),
    ]
