# Generated by Django 4.0.5 on 2022-07-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.utilisateur')),
                ('voy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.voyage')),
            ],
        ),
    ]
