# Generated by Django 4.0.5 on 2022-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_avion_voyage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='num',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
