# Generated by Django 4.0.5 on 2022-07-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_contact_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='client',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('resid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seatNo', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.utilisateur')),
                ('voy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.voyage')),
            ],
        ),
    ]
