# Generated by Django 4.0.5 on 2022-07-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_card_client_alter_card_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card',
        ),
    ]
